### ISSUE TITLE
可否增加蝌蚪形状的逗号、引号

### ISSUE THREAD

**Issue by stone-zeng** [Buernia/Zhudou-Sans#1]
思源字体默认的逗号、引号等也是蝌蚪形状的，可否考虑增加这一风格样式集？

**Comment by Buernia** [comment]
之前也考虑过，不过我没在 Noto Sans 里找到现成的蝌蚪逗号样式，所以就没做。可能之后会再寻找类似风格的字形，或是自行绘制。

**Comment by MY1L** [comment]
咦，不能从思源里提取逗号吗？

**Comment by Buernia** [comment]
> 咦，不能从思源里提取逗号吗？

一是 Source Sans 和 Noto Sans 的风格还是有差异的。二是我也不太喜欢思源黑体的这种逗号，要不然也不会有这个项目了。

**Comment by MY1L** [comment]
我在Monu和Ctrl里各做了2种口哨形逗号（含可变形式），也许用得着？

**Comment by Buernia** [comment]
完成，基于类似字形绘制了蝌蚪逗号。
