### ISSUE TITLE
Release 中的字体无法在 Word 或 LaTeX 中使用

### ISSUE THREAD

**Issue by syvshc** [Buernia/Zhudou-Sans#2]
系统: Win10 21H2
Word: Office 365 Beta 版
LaTeX: texlive 2021

下载了 [Zhudou Sans.zip](https://github.com/Buernia/Zhudou-Sans/releases/download/v1.000/Zhudou.Sans.zip) 后选择为所有人安装, 但是在 Word 中

![Zhudou-Sans-word](https://user-images.githubusercontent.com/38098591/155255639-470cc07e-2fd3-453c-a760-84117f7ee3cd.gif)

在 LaTeX 中:

```tex
\documentclass{ctexart}
% 这里我将 Zhudou Sans Regular.ttf 放在了该 `.tex` 文件的同级文件夹下
\setCJKmainfont{Zhudou Sans Regular.ttf}
\begin{document}
  中文
\end{document}
```

使用 xelatex 编译后显示

```
Package xeCJK Warning: Redefining CJKfamily `\CJKrmdefault' (SimSun(0)).

(./main.aux)
Missing character: There is no 中 (U+4E2D) in font [Zhudou Sans Regular.ttf]/OT:
script=hani;language=dflt;!
Missing character: There is no 文 (U+6587) in font [Zhudou Sans Regular.ttf]/OT:
script=hani;language=dflt;!
[1] (./main.aux) )
```

main 分支中的字体表现相同, 请问我可以通过什么方法来进行排查错误吗?

**Comment by Buernia** [comment]
还请注意相关说明，本字体是**标点符号**字体，不包含汉字或一般西文，只有标点符号、全角字母数字和少量特殊符号。字体自然无法在汉字上生效。

本字体需要与其他字体混排使用，替换其他字体的标点符号。汉字字体推荐思源黑体，西文字体则推荐 Noto Sans。

非常抱歉让您产生了误解，我之后会在 Readme 中强调这一点。

**Comment by syvshc** [comment]
抱歉, 是我阅读 README 不仔细, 谢谢您的回复
