### ISSUE TITLE
PS省略号不居中

### ISSUE THREAD

**Issue by CaiMiao** [Buernia/Zhudou-Sans#4]
是否可考虑增加居中的省略号？虽然在[GB/T 15834-2011](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)没有规定横排是否居中，但规定了竖排是需要居中的。 (5.2.2)

**Comment by Buernia** [comment]
本字体的省略号在横排和竖排中皆是居中位置，并没有沉底的字形。省略号在中西文里共用同一个编码（`U+2026`），还请确认省略号是否使用的是西文字体。

![图片](https://user-images.githubusercontent.com/11886946/175045217-5b5c085d-47c1-4c6b-a154-1c085ca77d53.png)

> 如图，省略号（`U+2026`）在竖排时会调用专门的竖排字形（`U+FE19`），在部分排版引擎中也有可能直接顺时针旋转90°。

**Comment by CaiMiao** [comment]
奇怪了 重启了一下ps又好了，，，可以关了

发自我的iPad

在 2022/06/22，21:53，奈白不弍 ***@***.***> 写道：

﻿

本字体的省略号在横排和竖排中皆是居中位置，并没有沉底的字形。省略号在中西文里共用同一个编码（U+2026），还请确认省略号是否使用的是西文字体。

[图片]<https://user-images.githubusercontent.com/11886946/175045217-5b5c085d-47c1-4c6b-a154-1c085ca77d53.png>

如图，省略号（U+2026）在竖排时会调用专门的竖排字形（U+FE19），在部分排版引擎中也有可能直接顺时针旋转90°。

**Comment by CaiMiao** [comment]
![图片](https://user-images.githubusercontent.com/4640483/175151090-81b6a6b8-9ebc-4231-aba4-ca7f61ba527d.png)

调错字体了，确实还是居左的，不知道为什么

**Comment by Buernia** [comment]
在 PS（2019）、AI（2019）、ID（2020）里简单测试了一下，这个问题只出现在 PS 中。且不只省略号，间隔号、破折号等中西文共用码位的标点都出现了向左偏移的现象。有待进一步查找原因。

**Comment by CaiMiao** [comment]
我是在ps cc2018环境使用的 竖排居左了

发自我的iPad

在 2022/06/22，21:53，奈白不弍 ***@***.***> 写道：

﻿

本字体的省略号在横排和竖排中皆是居中位置，并没有沉底的字形。省略号在中西文里共用同一个编码（U+2026），还请确认省略号是否使用的是西文字体。

[图片]<https://user-images.githubusercontent.com/11886946/175045217-5b5c085d-47c1-4c6b-a154-1c085ca77d53.png>

如图，省略号（U+2026）在竖排时会调用专门的竖排字形（U+FE19），在部分排版引擎中也有可能直接顺时针旋转90°。

**Comment by Buernia** [comment]
已在新版本中解决。
