### ISSUE TITLE
Different spacing behaviors in Chinese and Japanese text

### ISSUE THREAD

**Issue by Honoka55** [Buernia/Zhudou-Sans#5]
When multiple question marks or exclamation marks are used consecutively in Chinese text, the font appears to compress the space between them. While in Japanese text, the space between these marks remains consistent.

![QQ截图20230303153006](https://user-images.githubusercontent.com/71088406/222659718-41255792-426a-4486-9a86-0400f39d1a34.png)

**Comment by Buernia** [comment]
正常。中国内地标准感叹号和问号偏左，复用时自然压缩右侧宽度。日本标准感叹号和问号居中，复用时不会压缩宽度。
