### ISSUE TITLE
中文标点支援 VS selector

### ISSUE THREAD

**Issue by NightFurySL2001** [Buernia/Zhudou-Sans#6]
目前 Unicode 为以下 8 个中文标点符号定义了异体字选择器 (variation selector)，分别为左下角和置种式标点，请问本字体有计划支援吗？
<html>
<body>

U+ | 3002 | 3001 | FF01 | FF0C | FF0E | FF1A | FF1B | FF1F | 位置
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
基本字符 | 。 | 、 | ！ | ， | ． | ： | ； | ？ |  
基本字符 + VS01 | 。︀ | 、︀ | ！︀ | ，︀ | ．︀ | ：︀ | ；︀ | ？︀ | 左下角
基本字符 + VS02 | 。︁ | 、︁ | ！︁ | ，︁ | ．︁ | ：︁ | ；︁ | ？︁ | 置中

</body>
</html>

**Comment by Buernia** [comment]
现在发行的这个版本是支援的，参见 readme：

> 此外，本字体亦支持变体选择符（Variation Selector，VS）功能，在相应字符后输入变体选择符 VS01（`U+FE00`）或 VS02（`U+FE01`）即可强制将该字符显示为规定的变体字形。

不过源文件迁移到 Glyphs 后实现起来似乎有点问题，所以用 Glyphs 重制的新版本至今还没有发布。
