### ISSUE TITLE
可否提供仅将引号（“”‘’）修改为半宽的特性？

### ISSUE THREAD

**Issue by Bejukoro** [Buernia/Zhudou-Sans#8]
在部分中文字体的 UI Style （如更纱黑体、Mi Sans 等），中文标点中大多仅引号（“” ‘’）为半宽。
这样处理是为了在其他中文标点仍为全宽的情况下，使弯引号（“”‘’）仅与字母一同呈现或中英混排时不会产生违和感。
而当前煮豆黑体仅支持一并开启所有标点的半宽样式或全宽样式，用于 UI 时效果不够完美。尽管此情况在 Adobe 软件中能够解决，但在其他场合则暂无解决方法。请问可否提供单独的将上述弯引号修改为半宽的 UI 字体？

**Comment by Buernia** [comment]
这种情况下的 “半宽/半角弯引号” 实际上应该是宽度不等的 “比例宽度”，单引号宽度会比双引号更窄，而非统一的半个汉字宽度。

可以启用比例宽度字形（`pwid`）特性，该特性只影响引号的字形。而在无法操作 OpenType 特性的环境下，建议另外指定西文字体，覆盖本字体的全宽弯引号。
